import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar/SideBar";
import { Nunito_Sans } from "next/font/google";
import StoreProvider from "@/lib/StoreProvider";

const font = Nunito_Sans({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={font.className}>
          <div className="flex">
            <div className="mr-64">
              <SideBar />
            </div>
            <main className="w-full">{children}</main>
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
